// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdV5TsLlKdd0oPdoDXqNG0Ywc0uvaOkKE',
    appId: '1:94689994932:web:25c838f64a9cf496e48fe1',
    messagingSenderId: '94689994932',
    projectId: 'zethic-assignment',
    authDomain: 'zethic-assignment.firebaseapp.com',
    storageBucket: 'zethic-assignment.appspot.com',
    measurementId: 'G-3WEFN5726M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGq51__k7CL5LKlhqbAMnOSz3ejSEfwNs',
    appId: '1:94689994932:android:3f828552eb9e6a0be48fe1',
    messagingSenderId: '94689994932',
    projectId: 'zethic-assignment',
    storageBucket: 'zethic-assignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGtWuDoo2rwPNYGyCFvmAP8qbS8Vb4b9s',
    appId: '1:94689994932:ios:90a4aed4dd66caa4e48fe1',
    messagingSenderId: '94689994932',
    projectId: 'zethic-assignment',
    storageBucket: 'zethic-assignment.appspot.com',
    iosClientId: '94689994932-nca2fo2rtf66siqp4c80ssa4al4jiprk.apps.googleusercontent.com',
    iosBundleId: 'com.example.zethicAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGtWuDoo2rwPNYGyCFvmAP8qbS8Vb4b9s',
    appId: '1:94689994932:ios:90a4aed4dd66caa4e48fe1',
    messagingSenderId: '94689994932',
    projectId: 'zethic-assignment',
    storageBucket: 'zethic-assignment.appspot.com',
    iosClientId: '94689994932-nca2fo2rtf66siqp4c80ssa4al4jiprk.apps.googleusercontent.com',
    iosBundleId: 'com.example.zethicAssignment',
  );
}
